-- =============================================================================
-- Bank Transactions DWH — analytical queries (OLAP over the star schema)
-- Each query is annotated with the OLAP operation(s) it demonstrates:
-- slice, dice, drill-down, drill-through, pivot, ranking/window functions.
-- Dates below assume the sample data generated by data/generate_sample_data.py
-- (which spans 2024-2025) — adjust the year/quarter filters if you loaded
-- a different period.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Volume and turnover by service channel for a month
--    OLAP operations: slice (fixed month) + dice (group by channel)
-- -----------------------------------------------------------------------------
SELECT ch.channel_name                    AS "channel",
       COUNT(*)                           AS "transaction_count",
       SUM(f.amount)                      AS "total_amount"
FROM fact_transactions f
JOIN dim_date d    ON f.date_id = d.date_id
JOIN dim_channel ch ON f.channel_id = ch.channel_id
WHERE d.year = 2025 AND d.month = 10
GROUP BY ch.channel_name
ORDER BY SUM(f.amount) DESC;

-- -----------------------------------------------------------------------------
-- 1b. Same report, drilled down one level: channel x transaction type
--     OLAP operation: drill-down
-- -----------------------------------------------------------------------------
SELECT ch.channel_name, t.type_name,
       COUNT(*)      AS txn_count,
       SUM(f.amount) AS total_amount
FROM fact_transactions f
JOIN dim_date d              ON f.date_id = d.date_id
JOIN dim_channel ch          ON f.channel_id = ch.channel_id
JOIN dim_transaction_type t  ON f.type_id = t.type_id
WHERE d.year = 2025 AND d.month = 10
GROUP BY ch.channel_name, t.type_name
ORDER BY ch.channel_name, total_amount DESC;

-- -----------------------------------------------------------------------------
-- 2. Top-5 customers by transaction volume for the year
--    OLAP operation: ranking via window function (RANK)
-- -----------------------------------------------------------------------------
SELECT cus.full_name, cus.segment,
       SUM(f.amount) AS total_amount,
       RANK() OVER (ORDER BY SUM(f.amount) DESC) AS rnk
FROM fact_transactions f
JOIN dim_date d       ON f.date_id = d.date_id
JOIN dim_customer cus ON f.customer_id = cus.customer_id
WHERE d.year = 2025
GROUP BY cus.customer_id, cus.full_name, cus.segment
ORDER BY total_amount DESC
LIMIT 5;

-- -----------------------------------------------------------------------------
-- 3. Distribution of transactions by type with average ticket size
--    OLAP operation: aggregation (COUNT/SUM/AVG)
-- -----------------------------------------------------------------------------
SELECT t.type_name              AS "transaction_type",
       COUNT(*)                 AS "count",
       SUM(f.amount)            AS "total_amount",
       AVG(f.amount)            AS "average_amount"
FROM fact_transactions f
JOIN dim_transaction_type t ON f.type_id = t.type_id
WHERE f.transaction_time BETWEEN '2025-01-01' AND '2025-12-31'
GROUP BY t.type_name
ORDER BY SUM(f.amount) DESC;

-- -----------------------------------------------------------------------------
-- 4. Channel x quarter matrix ("pivot")
--    OLAP operation: pivot via conditional aggregation (CASE WHEN)
-- -----------------------------------------------------------------------------
SELECT ch.channel_name,
       SUM(CASE WHEN d.quarter = 1 THEN f.amount ELSE 0 END) AS q1,
       SUM(CASE WHEN d.quarter = 2 THEN f.amount ELSE 0 END) AS q2,
       SUM(CASE WHEN d.quarter = 3 THEN f.amount ELSE 0 END) AS q3,
       SUM(CASE WHEN d.quarter = 4 THEN f.amount ELSE 0 END) AS q4
FROM fact_transactions f
JOIN dim_date d     ON f.date_id = d.date_id
JOIN dim_channel ch ON f.channel_id = ch.channel_id
WHERE d.year = 2025
GROUP BY ch.channel_name;

-- =============================================================================
-- Appendix — extended queries: window functions, conditional aggregation,
-- multi-dimensional breakdowns, drill-through
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 5. Share of transactions processed under 5 seconds
--    OLAP operation: conditional aggregation (SLA-style metric).
--    Requires a processing_time interval column — not part of the base
--    schema in 01_schema_postgresql.sql; add it if you track SLA timing.
-- -----------------------------------------------------------------------------
-- SELECT
--     100.0 * SUM(CASE WHEN f.processing_time <= interval '5 seconds' THEN 1 ELSE 0 END)
--         / COUNT(*) AS perc_fast
-- FROM fact_transactions f
-- WHERE f.date_id IN (SELECT date_id FROM dim_date WHERE year = 2025);

-- -----------------------------------------------------------------------------
-- 6. Monthly trend for one customer segment
--    OLAP operation: drill-down over time
-- -----------------------------------------------------------------------------
SELECT d.year, d.month,
       COUNT(*)      AS txn_count,
       SUM(f.amount) AS total_amount
FROM fact_transactions f
JOIN dim_date d     ON f.date_id = d.date_id
JOIN dim_customer c ON f.customer_id = c.customer_id
WHERE c.segment = 'Mass Market' AND d.year = 2025
GROUP BY d.year, d.month
ORDER BY d.year, d.month;

-- -----------------------------------------------------------------------------
-- 7. Slice-and-dice: transfer volume by customer region, Q1 2025 only
--    OLAP operations: slice (quarter + type) + dice (group by region)
-- -----------------------------------------------------------------------------
SELECT c.region, SUM(f.amount) AS total_amount
FROM fact_transactions f
JOIN dim_date d             ON f.date_id = d.date_id
JOIN dim_customer c         ON f.customer_id = c.customer_id
JOIN dim_transaction_type t ON f.type_id = t.type_id
WHERE d.year = 2025 AND d.quarter = 1 AND t.type_name = 'Transfer'
GROUP BY c.region
ORDER BY 2 DESC;

-- -----------------------------------------------------------------------------
-- 8. Drill-through: full transaction list for one customer in a given month
--    OLAP operation: drill-through (aggregate report -> raw fact rows)
-- -----------------------------------------------------------------------------
SELECT f.transaction_id, d.calendar_date, f.amount, f.currency,
       t.type_name, ch.channel_name
FROM fact_transactions f
JOIN dim_date d              ON f.date_id = d.date_id
JOIN dim_customer c          ON f.customer_id = c.customer_id
JOIN dim_transaction_type t  ON f.type_id = t.type_id
JOIN dim_channel ch          ON f.channel_id = ch.channel_id
WHERE c.full_name = 'Ivanov I.I.' AND d.year = 2025 AND d.month = 1;

-- -----------------------------------------------------------------------------
-- 9. Each channel's share of total transaction volume
--    OLAP operation: window function without GROUP BY collapse (SUM ... OVER ())
-- -----------------------------------------------------------------------------
SELECT channel_name, txn_count, total_amount,
       total_amount * 100.0 / SUM(total_amount) OVER () AS pct_of_total
FROM (
    SELECT ch.channel_name, COUNT(*) AS txn_count, SUM(f.amount) AS total_amount
    FROM fact_transactions f
    JOIN dim_channel ch ON f.channel_id = ch.channel_id
    GROUP BY ch.channel_name
) t
ORDER BY total_amount DESC;

-- -----------------------------------------------------------------------------
-- 10. Average transactions per client, by segment and transaction type
--     OLAP operation: multi-dimensional aggregation with a derived ratio metric
-- -----------------------------------------------------------------------------
SELECT c.segment, t.type_name,
       COUNT(*) * 1.0 / COUNT(DISTINCT c.customer_id) AS avg_tx_per_client
FROM fact_transactions f
JOIN dim_customer c         ON f.customer_id = c.customer_id
JOIN dim_transaction_type t ON f.type_id = t.type_id
JOIN dim_date d              ON f.date_id = d.date_id
WHERE d.year = 2025 AND d.quarter = 1
GROUP BY c.segment, t.type_name;
